In [17]:
import numpy as np
x=np.array(([2,9],[1,5],[3,6]),dtype=float)
print(x)
y=np.array(([92],[86],[89]),dtype=float)
x=x/np.max(x,axis=0)
y=y/100
print(x)
print(y)

[[2. 9.]
 [1. 5.]
 [3. 6.]]
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]


In [18]:
def sigmoid(x):
    return (1/(1+np.exp(-x)))
def derivatives_sigmoid(x):
    return x*(1-x)
epoch=1000
lr=0.01
input_layer_neurons=2
hidden_layer_neurons=2
output_neurons=1
wh=np.random.uniform(size=(input_layer_neurons,hidden_layer_neurons))
bh=np.random.uniform(size=(1,hidden_layer_neurons))
wout=np.random.uniform(size=(hidden_layer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

In [19]:
for i in range(epoch):
    hinp1=np.dot(x,wh)
    hinp=hinp1+bh
    hlayer_act=sigmoid(hinp)
    outinp1=np.dot(hlayer_act,wout)
    outinp=outinp1+bout
    output=sigmoid(outinp)
    EO=(y-output)

In [20]:
outgrad=derivatives_sigmoid(output)
d_output=EO*outgrad
EH=d_output.dot(wout.T)
hiddengrad=derivatives_sigmoid(hlayer_act)
d_hiddenlayer=EH*hiddengrad

In [21]:
wout+=hlayer_act.T.dot(d_output)*lr
bout+=np.sum(d_output,axis=0,keepdims=True)*lr
wh+=x.T.dot(d_hiddenlayer)*lr
bh+=np.sum(d_hiddenlayer,axis=0,keepdims=True)*lr
print("-----------Epoch-",i+1,"Starts-----------")
print("Input:\n"+str(x))
print("Actual output:\n"+str(y))


-----------Epoch- 1000 Starts-----------
Input:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output:
[[0.92]
 [0.86]
 [0.89]]


In [22]:
print("predicted output:\n",output)
print("Error:\n"+str(EO))
print("--------Epoch-",i+1,"Ends------")
#

predicted output:
 [[0.79208538]
 [0.77963939]
 [0.79217299]]
Error:
[[0.12791462]
 [0.08036061]
 [0.09782701]]
--------Epoch- 1000 Ends------


In [14]:
print("Actual Output"+str(y))
print("Predicted Output"+str(output))
print("Error"+str(EO))

Actual Output[[0.92]
 [0.86]
 [0.89]]
Predicted Output[[0.77510513]
 [0.75225585]
 [0.77474039]]
Error[[0.14489487]
 [0.10774415]
 [0.11525961]]
